### ISSUE TITLE
Reverse Engineered ChatGPT doesn't work since `revChatGPT`'s proxy server is not available.

### ISSUE THREAD

**Issue by sunghyouk** [code-yeongyu/YGK-a#11]
안녕하세요, 어제부터 쓰기 시작했는데, 매우 잘 되서 감사하게 생각하고 있습니다.
(설치 시 다른 이슈는 없었습니다.)

오늘 갑자기 안 되어서 문의를 드리게 되었습니다.

현재 safari에서 chatGPT를 사용 중이고, 인터넷 연결도 안정적입니다.
물론 웹브라우저 상에서 chatGPT는 매우 잘 되고 있습니다.

그런데 위 스크린샷처럼 command line에서는 ygka "Hello"를 날리면
YGKA is waiting for chatGPT's answer ...
이렇게 나온 후 

<!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>

<title>chatgpt.duti.tech | 522: Connection timed out</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />

</head>
<body>
<div id="cf-wrapper">

    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark
leading-tight mr-2">

              <span class="inline-block">Connection timed out</span>
              <span class="code-label">Error code 522</span>
            </h1>
            <div>
               Visit <a
href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=chatgpt.duti.tech"
target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">2023-03-09 03:05:59 UTC</div>
        </header>

        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">

<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left
md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none
text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6
-bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Browser

  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left
md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none
text-center">
  <div class="relative mb-10 md:m-0">
    <a
href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=chatgpt.duti.tech"
target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6
-bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">Seattle</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    <a
href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=chatgpt.duti.tech"
target="_blank" rel="noopener noreferrer">
    Cloudflare
    </a>
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left
md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none
text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6
-bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">chatgpt.duti.tech</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Host

  </h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>

            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>The initial connection between Cloudflare's network and the origin web server timed
out. As a result, the web page can not be displayed.</p>
                </div>

                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                          <h3 class="text-15 font-semibold mb-2">If you're a visitor of this website:</h3>
      <p class="mb-6">Please try again in a few minutes.</p>

      <h3 class="text-15 font-semibold mb-2">If you're the owner of this website:</h3>
      <p><span>Contact your hosting provider letting them know your web server is not completing requests.
An Error 522 means that the request was able to connect to your web server, but that the request didn't
finish. The most likely cause is that something on your server is hogging resources.</span> <a rel="noopener
noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522">Additional
troubleshooting information here.</a></p>
                </div>
            </div>

        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center
sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong
class="font-semibold">7a5018b18b7cebea</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to
reveal</button>
      <span class="hidden" id="cf-footer-ip">147.47.231.213</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a
rel="noopener noreferrer"
href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=chatgpt.duti.tech"
id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
  <script>(function(){function d(){var
b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in
b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElemen
tById("cf-footer-ip").classList.remove("hidden")}))}var
a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div>

    </div>
</div>
</body>
</html>

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/anaconda3/lib/python3.9/site-packages/ygka/cli/ygka.py:29 in ygka_command                   │
│                                                                                                  │
│   26 │   try:                                                                                    │
│   27 │   │   with console.status('''[green] YGKA is waiting for ChatGPT's answer ...[/green]'    │
│   28 │   │   │   prompt = _generate_prompt(stdin, query)                                         │
│ ❱ 29 │   │   │   response = query_client.query(prompt)                                           │
│   30 │   │   │   console.print(response)                                                         │
│   31 │   except KeyError:                                                                        │
│   32 │   │   rich.print('It looks like the `session_token` is expired. Please reconfigure YGK    │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ config_manager = <ygka.utils.ygka_config_manager.YGKAConfigManager object at 0x7fa5e37aafa0> │ │
│ │        console = <console width=108 ColorSystem.TRUECOLOR>                                   │ │
│ │ language_model = None                                                                        │ │
│ │         prompt = 'Hello'                                                                     │ │
│ │          query = 'Hello'                                                                     │ │
│ │   query_client = <ygka.query_clients.reverse_engineered_chatgpt_client.ReverseEngineeredCha… │ │
│ │                  object at 0x7fa5e37aaf40>                                                   │ │
│ │          stdin = None                                                                        │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /opt/anaconda3/lib/python3.9/site-packages/ygka/query_clients/reverse_engineered_chatgpt_client. │
│ py:42 in query                                                                                   │
│                                                                                                  │
│   39 │   │   # ignore for wrong type hint of revchatgpt                                          │
│   40 │   │                                                                                       │
│   41 │   │   response_text = ''                                                                  │
│ ❱ 42 │   │   for data in chatbot.ask(prompt):                                                    │
│   43 │   │   │   response_text = data['message']                                                 │
│   44 │   │                                                                                       │
│   45 │   │   response_text = cast(str, response_text)                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │       chatbot = <revChatGPT.V1.Chatbot object at 0x7fa5e37c1cd0>                             │ │
│ │        prompt = 'Hello'                                                                      │ │
│ │ response_text = ''                                                                           │ │
│ │          self = <ygka.query_clients.reverse_engineered_chatgpt_client.ReverseEngineeredChat… │ │
│ │                 object at 0x7fa5e37aaf40>                                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /opt/anaconda3/lib/python3.9/site-packages/revChatGPT/V1.py:509 in ask                           │
│                                                                                                  │
│    506 │   │   │   timeout=timeout,                                                              │
│    507 │   │   │   stream=True,                                                                  │
│    508 │   │   )                                                                                 │
│ ❱  509 │   │   self.__check_response(response)                                                   │
│    510 │   │   for line in response.iter_lines():                                                │
│    511 │   │   │   # remove b' and ' at the beginning and end and ignore case                    │
│    512 │   │   │   line = str(line)[2:-1]                                                        │
│                                                                                                  │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮        │
│ │ conversation_id = None                                                                │        │
│ │            data = {                                                                   │        │
│ │                   │   'action': 'next',                                               │        │
│ │                   │   'messages': [                                                   │        │
│ │                   │   │   {                                                           │        │
│ │                   │   │   │   'id': '85f21846-d389-4022-a08c-07ef319cf09d',           │        │
│ │                   │   │   │   'role': 'user',                                         │        │
│ │                   │   │   │   'content': {                                            │        │
│ │                   │   │   │   │   'content_type': 'text',                             │        │
│ │                   │   │   │   │   'parts': ['Hello']                                  │        │
│ │                   │   │   │   }                                                       │        │
│ │                   │   │   }                                                           │        │
│ │                   │   ],                                                              │        │
│ │                   │   'conversation_id': None,                                        │        │
│ │                   │   'parent_message_id': 'df6a01fe-cf5e-43bf-ad11-68f977ebb091',    │        │
│ │                   │   'model': 'text-davinci-002-render-sha'                          │        │
│ │                   }                                                                   │        │
│ │       parent_id = 'df6a01fe-cf5e-43bf-ad11-68f977ebb091'                              │        │
│ │          prompt = 'Hello'                                                             │        │
│ │        response = <Response [522]>                                                    │        │
│ │            self = <revChatGPT.V1.Chatbot object at 0x7fa5e37c1cd0>                    │        │
│ │         timeout = 360                                                                 │        │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯        │
│                                                                                                  │
│ /opt/anaconda3/lib/python3.9/site-packages/revChatGPT/V1.py:58 in wrapper                        │
│                                                                                                  │
│     55 │   │   │   │   kwargs,                                                                   │
│     56 │   │   │   )                                                                             │
│     57 │   │   │   start = time.time()                                                           │
│ ❱   58 │   │   │   out = func(*args, **kwargs)                                                   │
│     59 │   │   │   end = time.time()                                                             │
│     60 │   │   │   if is_timed:                                                                  │
│     61 │   │   │   │   log.debug(                                                                │
│                                                                                                  │
│ ╭──────────────────────────────────── locals ─────────────────────────────────────╮              │
│ │     args = (<revChatGPT.V1.Chatbot object at 0x7fa5e37c1cd0>, <Response [522]>) │              │
│ │     func = <function Chatbot.__check_response at 0x7fa5e2d58670>                │              │
│ │ is_timed = False                                                                │              │
│ │   kwargs = {}                                                                   │              │
│ │    start = 1678331159.7190442                                                   │              │
│ ╰─────────────────────────────────────────────────────────────────────────────────╯              │
│                                                                                                  │
│ /opt/anaconda3/lib/python3.9/site-packages/revChatGPT/V1.py:627 in __check_response              │
│                                                                                                  │
│    624 │   │   """                                                                               │
│    625 │   │   if response.status_code != 200:                                                   │
│    626 │   │   │   print(response.text)                                                          │
│ ❱  627 │   │   │   raise Error(                                                                  │
│    628 │   │   │   │   source="OpenAI",                                                          │
│    629 │   │   │   │   message=response.text,                                                    │
│    630 │   │   │   │   code=response.status_code,                                                │
│                                                                                                  │
│ ╭────────────────────────── locals ───────────────────────────╮                                  │
│ │ response = <Response [522]>                                 │                                  │
│ │     self = <revChatGPT.V1.Chatbot object at 0x7fa5e37c1cd0> │                                  │
│ ╰─────────────────────────────────────────────────────────────╯                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
Error: OpenAI: <!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>

<title>chatgpt.duti.tech | 522: Connection timed out</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />

</head>
<body>
<div id="cf-wrapper">

    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark
leading-tight mr-2">

              <span class="inline-block">Connection timed out</span>
              <span class="code-label">Error code 522</span>
            </h1>
            <div>
               Visit <a
href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=chatgpt.duti.tech"
target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">2023-03-09 03:05:59 UTC</div>
        </header>

        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">

<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left
md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none
text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6
-bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Browser

  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left
md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none
text-center">
  <div class="relative mb-10 md:m-0">
    <a
href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=chatgpt.duti.tech"
target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6
-bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">Seattle</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    <a
href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=chatgpt.duti.tech"
target="_blank" rel="noopener noreferrer">
    Cloudflare
    </a>
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left
md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none
text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6
-bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">chatgpt.duti.tech</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Host

  </h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>

            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>The initial connection between Cloudflare's network and the origin web server timed
out. As a result, the web page can not be displayed.</p>
                </div>

                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                          <h3 class="text-15 font-semibold mb-2">If you're a visitor of this website:</h3>
      <p class="mb-6">Please try again in a few minutes.</p>

      <h3 class="text-15 font-semibold mb-2">If you're the owner of this website:</h3>
      <p><span>Contact your hosting provider letting them know your web server is not completing requests.
An Error 522 means that the request was able to connect to your web server, but that the request didn't
finish. The most likely cause is that something on your server is hogging resources.</span> <a rel="noopener
noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522">Additional
troubleshooting information here.</a></p>
                </div>
            </div>

        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center
sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong
class="font-semibold">7a5018b18b7cebea</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to
reveal</button>
      <span class="hidden" id="cf-footer-ip">147.47.231.213</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a
rel="noopener noreferrer"
href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_522&utm_campaign=chatgpt.duti.tech"
id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
  <script>(function(){function d(){var
b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in
b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElemen
tById("cf-footer-ip").classList.remove("hidden")}))}var
a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div>

    </div>
</div>
</body>
</html>

 (code: 522)

재설치 후 같은 증상이 반복되어 문의드립니다.
좋은 유틸리티 감사합니다.

**Comment by sunghyouk** [comment]
time out issue인 것 같은데, 일단, 나중에 다시 시도해 보겠습니다.

**Comment by code-yeongyu** [comment]
안녕하세요! 상세한 내용과 함께 issue 주셔서 너무 감사합니다. 🙇‍♂️

현재 리버싱 된 ChatGPT 는 CloudFlare bypass 때문에 외부의 프록시서버를 경유해서 ChatGPT 를 호출하는 방식으로 되어있어요. 해당 프록시는 ChatGPT 모듈인 https://github.com/acheong08/ChatGPT 에서 제공하고있습니다.

그런데 README 에서 보시면 아시겠지만 최근에 비용 부담이 심해져서 프록시서버를 deprecated 시켰다고 하더라구요. 😅

해결 방안은 두가지입니다:

1. `official_chatgpt` 를 사용한다
2. 다른 프록시 서버가 공개될 때 까지 해당 패치를 기다린다
  - ygka 는 저도 사용하고 있는 만큼 제가 직접 프록시 서버를 호스팅 할 의향도 있는데, 개발자분께서 아직 프록시 서버 소스는 공개를 안하셨더라구요!

그래서 저도 일단은 official_chatgpt 를 사용하고있습니다.
제가 먼저 notice 를 했어야하는데, 이슈 주셔서 너무 감사합니다!

**Comment by code-yeongyu** [comment]
This issue should have fixed with the #12, but it looks like the new version of `revChatGPT` with new proxy still not works tho.

So I recommend users to use `official_chatgpt`. Thanks.

**Comment by code-yeongyu** [comment]
I'll patch the reverse_engineered api to be workable again once the `revChatGPT`'s issue is resolved

https://github.com/acheong08/ChatGPT/issues/1102
https://github.com/acheong08/ChatGPT/issues/1108

I am keep tracking on it.

**Comment by acheong08** [comment]
I fixed it in latest version

**Comment by acheong08** [comment]
I found a new bypass but not sure how long it'll last. I can't afford load balancing anymore so the server might crash if abused

**Comment by code-yeongyu** [comment]
@acheong08 Thank you for your kind reply! Actually never expected you to appear here 😅

One more question: Are the plans for open sourcing the server app gone?

**Comment by acheong08** [comment]
Everything gets patched too quickly. I don't think I'll open source this one.
