### ISSUE TITLE
Config file does not exist

### ISSUE THREAD

**Issue by xshapira** [code-yeongyu/YGK-a#23]
I installed the latest version of `YGKA`. But, I'm unable to access the config file as the system indicates that the file is missing.

![Screen Shot](https://user-images.githubusercontent.com/48856190/232264250-41968ca3-10e3-4345-b642-3eacd61297dd.JPG)

**Comment by code-yeongyu** [comment]
Did you run the ygka after you update it?

**Comment by xshapira** [comment]
Yes, I did it. The good news is I can open the config file, but the bad news is I'm getting this error:

![Screen Shot](https://user-images.githubusercontent.com/48856190/232327214-3987c091-8e6c-4277-b5e9-4c049ac906b8.JPG)

My config file looks like this:

![Screen Shot 1](https://user-images.githubusercontent.com/48856190/232327234-1ca33a47-a170-48b0-81ef-c095bd5d6064.JPG)

**Comment by code-yeongyu** [comment]
Checkout #24 for this. I am sorry but the Reversed engineered chatgpt api module stopped working for now.
